### ISSUE TITLE
Add decoder to decode with offset

### ISSUE THREAD

**Issue by ChristophP** [TSFoster/elm-bytes-extra#4]
`slice` is a great function to extract chunks out of a `Bytes` sequence. However, it would be very practical if one could have a quick way of decoding with offsets(where there's no easy access to `Bytes`). That's why I am proposing this offset Decoder as a combinator for a `Decoder`.

**Example Implementation**
```elm
-- in the Bytes.Extra.Decode module
withOffset : Int -> Decoder a -> Decoder a
withOffset offset decoder =
    Bytes.Decode.bytes (max 0 offset) |> andThen (\_ -> decoder)

-- can then be used like this
import Bytes.Decode exposing (float64)
import Bytes.Decode.Extra exposing (withOffset)

withOffset 8 float64 -- will first skip 8 bytes and then decode a 64 bit-float 
```
**Concrete use case**
I am currently trying to decode buffer data out of buffers in GLTF data (3d model format). In many cases the data is not densely packed, so it is necessary to skip some bytes while decoding to get to the later data.

PS: Thanks for this useful package. <3

**Comment by TSFoster** [comment]
Interesting, thanks for the suggestion and your use case. I can see that it would make sense to have something similar to `Bytes.Extra.drop` that works with `Decoder`s. And I can see how coupling the skipping of the `Bytes` with the next `Decoder` will lead to more elegant code for users of this package.

I'll get this added and publish it.

**Comment by TSFoster** [comment]
[Done](https://package.elm-lang.org/packages/TSFoster/elm-bytes-extra/1.3.0/Bytes-Decode-Extra#withOffset)

**Comment by ChristophP** [comment]
@TSFoster Wow incredible that was very fast. :-) Thank you for adding and doing it this quickly. I'll be a happy user :+1:
